JobsDocumentsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.JobsDocumentsBucket.name}

JobsDocumentsBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref JobsDocumentsBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: "*"
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.JobsDocumentsBucket.name}/*
